In [10]:
import pyscf
import numpy
from pyscf import gto, scf, ci,df,lib, dft
import scipy
from time import ctime, time
import numgrid

In [37]:
TimeStart = time()
mol = gto.Mole(                                                                                               
        atom='''
         N       -2.1988391019      1.8973746268      0.0000000000                 
         H       -1.1788391019      1.8973746268      0.0000000000                 
         H       -2.5388353987      1.0925460144     -0.5263586446                 
         H       -2.5388400276      2.7556271745     -0.4338224694 ''',
        basis='def2-tzvp',verbose=0
    ).build()
mf = scf.RHF(mol)
mf.init_guess = '1e'
print("Total energy: ",mf.kernel())
print("Total job time: %10.2f(wall)" %(time()-TimeStart))

Total energy:  -56.21735425613152
Total job time:       0.10(wall)


In [70]:
lib.num_threads(6)
TimeStart = time()
mol = gto.Mole(                                                                                               
        atom='''
         N       -2.1988391019      1.8973746268      0.0000000000                 
         H       -1.1788391019      1.8973746268      0.0000000000                 
         H       -2.5388353987      1.0925460144     -0.5263586446                 
         H       -2.5388400276      2.7556271745     -0.4338224694 ''',
        charge=1,spin=1,basis='aug-cc-pv5z',verbose=4
    ).build()
mf = scf.UHF(mol).density_fit(auxbasis="def2-tzvp-jkfit")
mf.init_guess = '1e'
mf.diis = 'diis'
print("Total energy:",mf.kernel())
print("Total job time: %10.2f(wall)" %(time()-TimeStart))
##================================================
## debug 3-center integrals
##================================================
#ri3fn = df.incore.aux_e2(mol,"sto-3g")
# print(ri3fn.shape)
# index = 0
# for ind_k in range(0,ri3fn.shape[2]):
#     for ind_j in range(0,ri3fn.shape[1]):
#         for ind_i in range(0,ri3fn.shape[0]):
#             x = ri3fn[ind_i][ind_j][ind_k]
#             if abs(x)>0.1:
#                 index += 1
#                 print("I= %3i J=%3i K=%3i Int=%16.8f" %(ind_i,ind_j,ind_k,x))
# print("Print out %i 3-center RI-V tensor elements" %index)
##======================================================
## for two-center auxiliary coulomb integrals
##======================================================
# ri3fn = df.incore.aux_e2(mol,"def2-svp-jkfit",intor='int3c2e_sph',aosym='s2ij')
# auxmol=df.addons.make_auxmol(mol,'def2-svp-jkfit')
# j2c=auxmol.intor('int2c2e',hermi=0)
# # j2c = scipy.linalg.inv(j2c)
# index = 0
# for ind_j in range(0,j2c.shape[1]):
#     for ind_i in range(0,j2c.shape[0]):
#         x = j2c[ind_i][ind_j]
#         if abs(x)>0.1:
#             index += 1
#             print("I= %3i J=%3i Int=%16.8f" %(ind_i,ind_j,x))
# print("Print out %i 2-center auxiliary coulomb elements" %index)
##======================================================
## for three-center tensors
##======================================================
# ri3fn = lib.unpack_tril(mf.with_df._cderi)
# index = 0
# for ind_k in range(0,ri3fn.shape[0]):
#     for ind_i in range(0,ri3fn.shape[1]):
#         for ind_j in range(0,ri3fn.shape[2]):
#             x = ri3fn[ind_k][ind_i][ind_j]
#             if abs(x)>0.1:
#                 index += 1
#                 print("I= %3i J=%3i K=%3i Int=%16.8f" %(ind_i,ind_j,ind_k,x))
# print("Print out %i 3-center RI-V tensor elements" %index)
##======================================================
## for ERI
##======================================================
# ri3fn = df.incore.aux_e2(mol,"def2-svp-jkfit",intor='int3c2e_sph',aosym='s2ij')
# auxmol=df.addons.make_auxmol(mol,'def2-svp-jkfit')
# j2c=auxmol.intor('int2c2e',hermi=0)
# eri1 = numpy.einsum('ik,kl->il',ri3fn,numpy.linalg.inv(j2c))
# eri1 = numpy.einsum('ip,kp->ik',eri1,ri3fn)
# index = 0
# for ind_ij in range(0,eri1.shape[0]):
#     for ind_kl in range(0,eri1.shape[1]):
#             x = eri1[ind_ij][ind_kl]
#             if abs(x)>0.1:
#                 index += 1
#                 print("IJ= %3i KL=%3i Int=%16.8f" %(ind_ij,ind_kl,x))
# print("Print out %i 4-center ERI elements" %index)

# mf.kernel()

System: uname_result(system='Linux', node='igor-Latitude-5591', release='5.4.0-120-generic', version='#136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022', machine='x86_64', processor='x86_64')  Threads 6
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]
numpy 1.16.4  scipy 1.2.1
Date: Wed Jun 22 21:37:21 2022
PySCF version 2.0.1
PySCF path  /home/igor/Data/opt/anaconda3/lib/python3.6/site-packages/pyscf

[CONFIG] conf_file None
[INPUT] verbose = 4
[INPUT] num. atoms = 4
[INPUT] num. electrons = 9
[INPUT] charge = 1
[INPUT] spin (= nelec alpha-beta = 2S) = 1
[INPUT] symmetry False subgroup None
[INPUT] Mole.unit = angstrom
[INPUT]  1 N     -2.198839101900   1.897374626800   0.000000000000 AA   -4.155203694576   3.585518400351   0.000000000000 Bohr
[INPUT]  2 H     -1.178839101900   1.897374626800   0.000000000000 AA   -2.227683047519   3.585518400351   0.000000000000 Bohr
[INPUT]  3 H     -2.538835398700   1.092546014400  -0.526358644600 AA   -4.797703578894   2.0646

[ 7 20  1 23  0  0]
[ 1 24  1 27  0  0]
[ 1 28  1 31  0  0]
[ 1 32  1 35  0  0]
0 [ 0  0  3  1  0 42 45  0]
[99.106169  18.052312   4.8856602]
[12.24723354 11.84499063  3.69156624]
1 [ 0  0  3  1  0 48 51  0]
[3.7804559 0.8784966 0.2857144]
[-0.68474806  0.91590581  0.69124784]
2 [ 0  1  3  1  0 54 57  0]
[3.7804559 0.8784966 0.2857144]
[2.39776185 1.50777694 0.23885724]
3 [ 1  0  3  1  0 36 39  0]
[3.42525091 0.62391373 0.1688554 ]
[0.98170675 0.94946401 0.29590645]
4 [ 2  0  3  1  0 36 39  0]
[3.42525091 0.62391373 0.1688554 ]
[0.98170675 0.94946401 0.29590645]
5 [ 3  0  3  1  0 36 39  0]
[3.42525091 0.62391373 0.1688554 ]
[0.98170675 0.94946401 0.29590645]
debug
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.         -4.15520369  3.5855184   0.          0.
 -2.22768305  3.5855184   0.          0.         -4.79770358  2.06

In [14]:
TimeStart = time()
mol = gto.Mole(                                                                                               
        atom='''
         N       -2.1988391019      1.8973746268      0.0000000000                 
         H       -1.1788391019      1.8973746268      0.0000000000                 
         H       -2.5388353987      1.0925460144     -0.5263586446                 
         H       -2.5388400276      2.7556271745     -0.4338224694 ''',
        basis='def2-tzvp',verbose=0
    ).build()
method = dft.RKS(mol)
print('Default DFT(LDA).  E = %.12f' % method.kernel())

# See pyscf/dft/radi.py for more radial grid schemes
#grids.radi_method = dft.gauss_chebeshev
#grids.radi_method = dft.delley
method = dft.RKS(mol)
method.grids.radi_method = dft.mura_knowles
print('Changed radial grids for DFT.  E = %.12f' % method.kernel())


# See pyscf/dft/gen_grid.py for detail of the grid weight scheme
#method.grids.becke_scheme = dft.original_becke
# Stratmann-Scuseria weight scheme
method = dft.RKS(mol)
method.grids.becke_scheme = dft.stratmann
print('Changed grid partition funciton.  E = %.12f' % method.kernel())

# Grids level 0 - 9.  Big number indicates dense grids. Default is 3
method = dft.RKS(mol)
method.grids.level = 4
print('Dense grids.  E = %.12f' % method.kernel())

# Specify mesh grid for certain atom
method = dft.RKS(mol)
method.grids.atom_grid = {'O': (100, 770)}
print('Dense grids for O atom.  E = %.12f' % method.kernel())

# Specify mesh grid for all atoms
method = dft.RKS(mol)
method.grids.atom_grid = (100, 770)
print('Dense grids for all atoms.  E = %.12f' % method.kernel())


# Disable pruning grids near core region
#grids.prune = dft.sg1_prune
method = dft.RKS(mol)
method.grids.prune = None
print('Changed grid partition funciton.  E = %.12f' % method.kernel())

print("Total job time: %10.2f(wall)" %(time()-TimeStart))

Default DFT(LDA).  E = -56.100667658113
Changed radial grids for DFT.  E = -56.100667683944
Changed grid partition funciton.  E = -56.100667820637
Dense grids.  E = -56.100667719163
Dense grids for O atom.  E = -56.100667658113
Dense grids for all atoms.  E = -56.100667729458
Changed grid partition funciton.  E = -56.100667639101
Total job time:       2.85(wall)


In [18]:
grids = dft.gen_grid.Grids(mol)
help(dft.gen_grid.Grids)

Help on class Grids in module pyscf.dft.gen_grid:

class Grids(pyscf.lib.misc.StreamObject)
 |  DFT mesh grids
 |  
 |  Attributes for Grids:
 |      level : int
 |          To control the number of radial and angular grids. Large number
 |          leads to large mesh grids. The default level 3 corresponds to
 |          (50,302) for H, He;
 |          (75,302) for second row;
 |          (80~105,434) for rest.
 |  
 |          Grids settings at other levels can be found in
 |          pyscf.dft.gen_grid.RAD_GRIDS and pyscf.dft.gen_grid.ANG_ORDER
 |  
 |      atomic_radii : 1D array
 |          | radi.BRAGG_RADII  (default)
 |          | radi.COVALENT_RADII
 |          | None : to switch off atomic radii adjustment
 |  
 |      radii_adjust : function(mol, atomic_radii) => (function(atom_id, atom_id, g) => array_like_g)
 |          Function to adjust atomic radii, can be one of
 |          | radi.treutler_atomic_radii_adjust
 |          | radi.becke_atomic_radii_adjust
 |          | N

-55.45144347014942

In [141]:
    from pyscf import scf
    from pyscf import ao2mo
    mol = gto.Mole()
    mol.verbose = 0
    mol.output = None

    mol.atom.extend([
        ["H", (0,  0, 0  )],
        ["H", (0,  0, 1  )],
    ])
    mol.basis = 'cc-pvdz'
    mol.build()

    auxmol = df.incore.format_aux_basis(mol)
    j3c = df.incore.aux_e2(mol, auxmol, intor='int3c2e_sph', aosym='s1')
    nao = mol.nao_nr()
    naoaux = auxmol.nao_nr()
    j3c = j3c.reshape(nao,nao,naoaux)

    atm, bas, env = \
            gto.mole.conc_env(mol._atm, mol._bas, mol._env,
                              auxmol._atm, auxmol._bas, auxmol._env)
    eri0 = numpy.empty((nao,nao,naoaux))
    pi = 0
    for i in range(mol.nbas):
        pj = 0
        for j in range(mol.nbas):
            pk = 0
            for k in range(mol.nbas, mol.nbas+auxmol.nbas):
                shls = (i, j, k)
                buf = gto.moleintor.getints_by_shell('int3c2e_sph',
                                                     shls, atm, bas, env)
                di, dj, dk = buf.shape
                eri0[pi:pi+di,pj:pj+dj,pk:pk+dk] = buf
                pk += dk
            pj += dj
        pi += di
    print(numpy.allclose(eri0, j3c))

    j2c = df.incore.fill_2c2e(mol, auxmol)
    eri0 = numpy.empty_like(j2c)
    pi = 0
    for i in range(mol.nbas, len(bas)):
        pj = 0
        for j in range(mol.nbas, len(bas)):
            shls = (i, j)
            buf = gto.moleintor.getints_by_shell('int2c2e_sph',
                                                 shls, atm, bas, env)
            di, dj = buf.shape
            eri0[pi:pi+di,pj:pj+dj] = buf
            pj += dj
        pi += di
    print(numpy.allclose(eri0, j2c))

    j3c = df.incore.aux_e2(mol, auxmol, intor='int3c2e_sph', aosym='s2ij')
    cderi = df.incore.cholesky_eri(mol, auxmol=auxmol)
    eri0 = numpy.einsum('pi,pk->ik', cderi, cderi)
    eri1 = numpy.einsum('ik,kl->il', j3c, numpy.linalg.inv(j2c))
    eri1 = numpy.einsum('ip,kp->ik', eri1, j3c)
    print(abs(eri1 - eri0).max())
    eri0 = ao2mo.restore(1, eri0, nao)

    mf = scf.RHF(mol)
    ehf0 = mf.scf()

    nao = mf.mo_energy.size
    eri1 = ao2mo.restore(1, mf._eri, nao)
    print(abs(eri1-eri0).max() - 0.0022142583265513105)

    mf._eri = ao2mo.restore(8, eri0, nao)
    ehf1 = mf.scf()

    mf = scf.RHF(mol).density_fit(auxbasis='weigend')
    ehf2 = mf.scf()

    mf = mf.density_fit(auxbasis='weigend')
    ehf3 = mf.scf()
    print(ehf0, ehf1, ehf2, ehf3)

True
True
4.883871085326064e-13
-2.7755575615628914e-15
-1.10015376487841 -1.1001547208961515 -1.100193764624759 -1.1001937646247586


In [3]:
radii, weights = numgrid.radial_grid_lmg( alpha_min={0: 0.3023, 1: 0.2753, 2: 1.185}, alpha_max=11720.0, radial_precision=1.0e-12, proton_charge=8, )

In [4]:
print(radii)

[1.2304794589759454e-06, 2.6336980993310114e-06, 4.233905675553877e-06, 6.058756210858283e-06, 8.13978590080707e-06, 1.0512958106784992e-05, 1.3219284857637214e-05, 1.630553559996809e-05, 1.9825045445384375e-05, 2.3838636882425878e-05, 2.8415670881768902e-05, 3.3635245559400795e-05, 3.95875631124901e-05, 4.637548865068543e-05, 5.4116327861820987e-05, 6.294385423279893e-05, 7.301062085911147e-05, 8.44905967945913e-05, 9.758217350152745e-05, 0.00011251159335718234, 0.00012953685946652218, 0.0001489521943486774, 0.00017109312455002314, 0.00019634227905373608, 0.0002251360016911716, 0.0002579718918275978, 0.0002954174036368161, 0.00033811965257322685, 0.0003868165985121067, 0.00044234979881978883, 0.000505678951746213, 0.000577898481471814, 0.0006602564514236075, 0.00075417613271137, 0.000861280600419329, 0.0009834207828147287, 0.0011227074482063066, 0.0012815476822342878, 0.001462686485975001, 0.0016692542137387164, 0.0019048206703580484, 0.002173456802850449, 0.0024798050525806402, 0.002